project_name: mouser

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/mouser
    env:
      - CGO_ENABLED=1
    goos:
      - darwin

brews:
  - repository:
      owner: echocrow
      name: homebrew-tap
    directory: Formula

    homepage: '{{ replace .GitURL ".git" "" }}'
    description: Automate actions via mouse gestures.
    license: LGPL-3.0-or-later

    caveats: |
      To configure and run mouser, create and edit the config file:
        mkdir -p "$(dirname "$(./mouser --config '?')")" && touch "$(./mouser --config '?')" && echo $_

      For examples on how to configure mouser, refer to the homepage:
        #{homepage}

      Note: The first time you run mouser you may need to provide additional
      permissions to the app:
        System Perferences > Security & Privacy > Privacy > Accessibility > mouser
      Once granted, restart mouser.

    service: |
      run opt_bin/"mouser"
      run_at_load true
      keep_alive successful_exit: false

    test: |
      system "#{bin}/mouser --version"
