// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	hotkey "github.com/birdkid/mouser/pkg/hotkeys/hotkey"
	mock "github.com/stretchr/testify/mock"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// Register provides a mock function with given fields: id, keyCode
func (_m *Engine) Register(id hotkey.ID, keyCode hotkey.KeyCode) bool {
	ret := _m.Called(id, keyCode)

	var r0 bool
	if rf, ok := ret.Get(0).(func(hotkey.ID, hotkey.KeyCode) bool); ok {
		r0 = rf(id, keyCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Unregister provides a mock function with given fields: id
func (_m *Engine) Unregister(id hotkey.ID) {
	_m.Called(id)
}
