// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	hotkey "github.com/echocrow/Mouser/pkg/hotkeys/hotkey"
	mock "github.com/stretchr/testify/mock"
)

// IDProvider is an autogenerated mock type for the IDProvider type
type IDProvider struct {
	mock.Mock
}

// NextID provides a mock function with given fields:
func (_m *IDProvider) NextID() hotkey.ID {
	ret := _m.Called()

	var r0 hotkey.ID
	if rf, ok := ret.Get(0).(func() hotkey.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(hotkey.ID)
	}

	return r0
}
