// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	hotkey "github.com/birdkid/mouser/pkg/hotkeys/hotkey"
	mock "github.com/stretchr/testify/mock"
)

// Registrar is an autogenerated mock type for the Registrar type
type Registrar struct {
	mock.Mock
}

// Add provides a mock function with given fields: key
func (_m *Registrar) Add(key hotkey.KeyName) (hotkey.ID, error) {
	ret := _m.Called(key)

	var r0 hotkey.ID
	if rf, ok := ret.Get(0).(func(hotkey.KeyName) hotkey.ID); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(hotkey.ID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hotkey.KeyName) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: id
func (_m *Registrar) Remove(id hotkey.ID) {
	_m.Called(id)
}
